apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: concourse-common-pvc
  namespace: concourse
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
