--- # PersistentVolumeClaim.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: concourse-db-pvc
  namespace: concourse
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
--- # Deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: concourse-db-deployment
  namespace: concourse
  labels:
    app: concourse-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: concourse-db
  template:
    metadata:
      labels:
        app: concourse-db
    spec:
      containers:
      - env:
        - name: PGDATA
          value: /var/lib/data/pgdata
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: concourse-config
              key: concourse.postgres.db
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: concourse-config
              key: concourse.postgres.user
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: concourse-config
              key: concourse.postgres.password
        - name: PGPORT
          value: "5432"
        name: concourse-db
        image: postgres:15.8-alpine3.20
        ports:
        - name: concourse-db
          containerPort: 5432
        volumeMounts:
        - name: concourse-db-data
          mountPath: /var/lib/data/pgdata
      restartPolicy: Always
      volumes:
      - name: concourse-db-data
        persistentVolumeClaim:
          claimName: concourse-db-pvc
--- # Service.yaml
apiVersion: v1
kind: Service
metadata:
  name: concourse-db-svc
  namespace: concourse
  labels:
    service: concourse-db
spec:
  type: ClusterIP
  selector:
    app: concourse-db
  ports:
  - name: ci-db-svc
    protocol: TCP
    port: 5432
    targetPort: concourse-db
