apiVersion: apps/v1
kind: Deployment
metadata:
  name: concourse-web
  labels:
    app: concourse-web

spec:
  replicas: 1
  selector:
    matchLabels:
      app: concourse-web
  strategy:
    type: Recreate

  template:
    metadata:
      labels:
        app: concourse-web
    spec:
      containers:
      - name: concourse-web
        image: concourse/concourse
        imagePullPolicy: IfNotPresent
        args:
          - web
        env:
        - name: CONCOURSE_ADD_LOCAL_USER
          value: concourse:concourse
        - name: CONCOURSE_MAIN_TEAM_LOCAL_USER
          value: concourse
        - name: CONCOURSE_EXTERNAL_URL
          value: http://debian.virt:32080
        - name: CONCOURSE_SESSION_SIGNING_KEY
          value: /concourse-keys/session_signing_key
        - name: CONCOURSE_TSA_HOST_KEY
          value: /concourse-keys/tsa_host_key
        - name: CONCOURSE_TSA_AUTHORIZED_KEYS
          value: /concourse-keys/authorized_worker_keys
        - name: CONCOURSE_POSTGRES_HOST
          value: concourse-db
        - name: CONCOURSE_POSTGRES_PORT
          value: "5432"
        - name: CONCOURSE_POSTGRES_DATABASE
          value: concourse
        - name: CONCOURSE_POSTGRES_USER
          value: concourse
        - name: CONCOURSE_POSTGRES_PASSWORD
          value: concourse

        ports:
        - name: concourse-web
          containerPort: 8080
        - name: concourse-ssh
          containerPort: 2222

        volumeMounts:
        - mountPath: /concourse-keys
          name: cache-volume

      volumes:
      - name: cache-volume
        secret:
          secretName: concourse-web-keys

