apiVersion: apps/v1
kind: Deployment
metadata:
  name: concourse-web-deployment
  namespace: concourse
  labels:
    app: concourse-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: concourse-web
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: concourse-web
    spec:
      containers:
      - args:
          - web
        env:
        - name: CONCOURSE_ADD_LOCAL_USER
          value: concourse:concourse,itas:itas
        - name: CONCOURSE_MAIN_TEAM_LOCAL_USER
          value: concourse
        - name: CONCOURSE_EXTERNAL_URL
          valueFrom: 
            configMapKeyRef:
              name: concourse-config
              key: concourse.external.url
        - name: CONCOURSE_SESSION_SIGNING_KEY
          value: /concourse-keys/session_signing_key
        - name: CONCOURSE_TSA_HOST_KEY
          value: /concourse-keys/tsa_host_key
        - name: CONCOURSE_TSA_AUTHORIZED_KEYS
          value: /concourse-keys/authorized_worker_keys
        - name: CONCOURSE_POSTGRES_HOST
          valueFrom: 
            configMapKeyRef:
              name: concourse-config
              key: concourse.postgres.host
        - name: CONCOURSE_POSTGRES_PORT
          valueFrom: 
            configMapKeyRef:
              name: concourse-config
              key: concourse.postgres.port
        - name: CONCOURSE_POSTGRES_DATABASE
          valueFrom:
            configMapKeyRef:
              name: concourse-config
              key: concourse.postgres.db
        - name: CONCOURSE_POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: concourse-config
              key: concourse.postgres.user
        - name: CONCOURSE_POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: concourse-config
              key: concourse.postgres.password
        name: concourse-web
        image: concourse/concourse
        imagePullPolicy: IfNotPresent
        ports:
        - name: concourse-web
          containerPort: 8080
        - name: concourse-ssh
          containerPort: 2222
        volumeMounts:
        - name: cache-volume
          mountPath: /concourse-keys
      volumes:
      - name: cache-volume
        secret:
          secretName: concourse-web-keys
