apiVersion: v1
kind: Service
metadata:
  name: concourse-web-svc
  namespace: concourse
  labels:
    service: concourse-web
spec:
  type: ClusterIP
  selector:
    app: concourse-web
  ports:
  - name: ci-web-http
    protocol: TCP
    port: 8080
    targetPort: concourse-web
  - name: ci-web-ssh
    protocol: TCP
    port: 2222
    targetPort: concourse-ssh
