apiVersion: v1
kind: ConfigMap
metadata:
  name: concourse-config
  namespace: concourse
data:
  concourse.tsa.host: "concourse-web-svc:2222"
  concourse.postgres.host: "concourse-db-svc"
  concourse.postgres.port: "5432"
  concourse.postgres.db: "concourse"
  concourse.postgres.user: "concourse"
  concourse.postgres.password: "concourse"
  concourse.external.url: "https://ci.concourse.com:32443"
  concourse.nginx.conf: |
    worker_processes auto;

    events {
      worker_connections 128;
    }

    http {
      ssl_session_timeout 10m;

      include /etc/nginx/conf.d/*.conf;
    }
  concourse.nginx.ci.concourse.com.conf: |
    server {
       listen 443 ssl;
       listen [::]:443 ssl;
       server_name ci.concourse.com;

       ssl_certificate /etc/nginx/ssl/ci.concourse.com/server.crt;
       ssl_certificate_key /etc/nginx/ssl/ci.concourse.com/server.key;
       ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;

       add_header Strict-Transport-Security "max-age=31536000" always;

       # Proxy web traffic
       location / {
          proxy_pass http://concourse-web-svc:8080/;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwared-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwared-Proto $scheme;
          proxy_set_header X-Forwared-Protocol $scheme;
          proxy_set_header X-Forwared-Host $http_host;
       }

       # Proxy fly intercept traffic
       location ~ /hijack$ {
          proxy_pass http://concourse-web-svc:8080;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwared-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwared-Proto $scheme;
          proxy_set_header X-Forwared-Protocol $scheme;
          proxy_set_header X-Forwared-Host $http_host;

          # Upgrade connection
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
       }
    }

