--- # Service.yaml
apiVersion: v1
kind: Service
metadata:
  name: concourse-db-svc
  namespace: concourse
  labels:
    service: concourse-db
spec:
  type: ClusterIP
  selector:
    app: concourse-db
  ports:
  - name: ci-db-svc
    protocol: TCP
    port: 5432
    targetPort: concourse-db
