apiVersion: v1
kind: Service
metadata:
  name: concourse-web
  labels:
    service: concourse-web

spec:
  type: NodePort
  selector:
    app: concourse-web
  ports:
  - name: con-web-svc
    protocol: TCP
    port: 8080
    targetPort: concourse-web
    nodePort: 32080

