apiVersion: v1
kind: Service
metadata:
  name: concourse-nginx-svc
  namespace: concourse
  labels:
    service: concourse-nginx
spec:
  type: NodePort
  selector:
    app: concourse-nginx
  ports:
  - name: ci-nginx-https
    protocol: TCP
    port: 443
    targetPort: concourse-nginx
    nodePort: 32443
