apiVersion: v1
kind: Service
metadata:
  name: concourse-db
  labels:
    service: concourse-db
spec:
  selector:
    app: concourse-db

  ports:
  - name: con-db-svc
    protocol: TCP
    port: 54321
    targetPort: concourse-db

  
