apiVersion: apps/v1
kind: Deployment
metadata:
  name: concourse-worker-deployment
  namespace: concourse
  labels:
    app: concourse-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: concourse-worker
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: concourse-worker
    spec:
      containers:
      - args:
          - worker
        env:
        - name: CONCOURSE_TSA_HOST
          valueFrom:
            configMapKeyRef:
              name: concourse-config 
              key: concourse.tsa.host
        - name: CONCOURSE_TSA_PUBLIC_KEY
          value: /concourse-keys/tsa_host_key.pub
        - name: CONCOURSE_RUNTIME
          value: containerd
        - name: CONCOURSE_TSA_WORKER_PRIVATE_KEY
          value: /concourse-keys/worker_key
        securityContext:
          privileged: true
          capabilities:
            add: ["NET_ADMIN", "NET_RAW"]
        name: concourse-worker
        image: concourse/concourse
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: cache-volume
          mountPath: /concourse-keys
      restartPolicy: Always
      volumes:
      - name: cache-volume
        secret:
          secretName: concourse-worker-keys
