apiVersion: v1
kind: Service
metadata:
  name: prometheus-svc
  namespace: monitoring
  labels:
    service: prometheus
spec:
  type: ClusterIP
  selector:
    app: prometheus
  ports:
  - name: prom-svc
    protocol: TCP
    port: 9090
    targetPort: prometheus
