apiVersion: v1
kind: Service
metadata:
  name: loki-service
  namespace: monitoring
  labels:
    service: loki
spec:
  type: ClusterIP 
  selector:
    app: loki
  ports:
  - name: loki-svc
    protocol: TCP
    port: 3100
    targetPort: loki
