apiVersion: v1
kind: LimitRange
metadata:
  name: default-limit-range
  namespace: monitoring
spec:
  limits:
  - default:
      cpu: 1000m
      memory: 1Gi
    defaultRequest:
      cpu: 500m
      memory: 500Mi
    max:
      cpu: 1000m
    min:
      cpu: 500m
    type: Container
