apiVersion: v1
kind: Service
metadata:
  name: grafana-svc
  namespace: monitoring
  labels:
    service: grafana
spec:
  type: ClusterIP
  selector:
    app: grafana
  ports:
  - name: grafana-svc
    protocol: TCP
    port: 3000
    targetPort: grafana
