apiVersion: v1
kind: LimitRange
metadata:
  name: default-limit-range
  namespace: monitoring
spec:
  limits:
  - default:
      cpu: 1000m
    defaultRequest:
      cpu: 500m
    max:
      cpu: 1000m
    min:
      cpu: 500m
  type: Container
