resources:
- name: tic-toc
  type: time
  source: {interval: 30m}

jobs:
- name: hello-world
  plan:
  - get: tic-toc
    trigger: true
  - task: say-hello
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: alpine}
      run:
        path: echo
        args: ["Hello, Concourse CI!"]

- name: do-some-cool-stuff
  plan:
  - get: tic-toc
    trigger: true
    passed: [hello-world]
  - task: lets-do-it
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: alpine}
      run:
        path: sh
        args:
        - -ec
        - | 
          whoami
          env
          find .
          echo "run a for loop"
          for i in $(seq 1 25); do printf "[$(date)] loop run $i\n"; done
          echo "end of a for loop"
